name: Chisel IP Contribution Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      uses: YosysHQ/setup-oss-cad-suite@v1
      with:
        osscadsuite-version: '2021-11-09'

    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: openjdk@1.11

    - name: Compile
      run: sbt compile

    - name: Unit Tests
      run: sbt test

  doc:
    name: Documentation and Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Documentation
        id: doc
        run: sbt doc
      - name: Check Formatting
        run: sbt scalafmtCheckAll
